services:
  publisher:
    image: localhost/go-pubsub-demo-publisher
    depends_on:
      - rabbitmq
    build:
      context: publisherService
      dockerfile: Dockerfile.development
    ports:
      - 8080:8080
    environment:
      - GOPROXY=direct
      - APP_ENV=dev
      - APP_CONFIG=/app/publisherService/configs/config.yaml
    volumes:
      - .:/app        # mount source code
  consumer:
    image: localhost/go-pubsub-demo-consumer
    depends_on:
      - rabbitmq
    build:
      context: consumerService
      dockerfile: Dockerfile.development
    environment:
      - GOPROXY=direct
      - APP_ENV=dev
      - APP_CONFIG=/app/consumerService/configs/config.yaml
    volumes:
      - .:/app        # mount source code
  rabbitmq:
    image: rabbitmq:4.1.2-management-alpine
    ports:
        - 15672:15672
    volumes:
        - lab_rabbitmq_data:/var/lib/rabbitmq/
        - lab_rabbitmq_logs:/var/log/rabbitmq/
volumes:
  lab_rabbitmq_data:
  lab_rabbitmq_logs:
