# .air.toml

[build]
  cmd = "cd /app/consumerService/cmd/consumer && go build -o /tmp/main"
  bin = "/tmp/main"
  full_bin = "/tmp/main"
  include_ext = ["go"]
  exclude_dir = ["tmp"]
  exclude_file = ["*_test.go"]

[log]
  time = true

[misc]
  # Delete tmp directory on exit
  clean_on_exit = true
